import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
	container: {
		flex: 3,
		flexDirection: 'row',
		justifyContent: 'space-between',
		padding: 20,
	},
	leftSide: {
		margin: 'auto',
		width: 280,
		marginBottom: 40,
	},
	titleLeft: {
		marginBottom: 16,
		fontWeight: '700',
		fontSize: 28,
		lineHeight: 34,
	},
	textH3Left: {
		marginBottom: 24,
		fontWeight: '400',
		fontSize: 24,
		lineHeight: 30,
	},
	textP: {
		marginBottom: 12,
		fontWeight: '500',
		fontSize: 18,
		lineHeight: 20,
	},
	listLeft: {
		flexDirection: 'column',
		gap: 16,
		marginBottom: 24,
	},
	itemLeft: {
		flexDirection: 'row',
		gap: 8,
		alignItems: 'center',
		fontWeight: '400',
		fontSize: 16,
		lineHeight: 20,
		width: 224,
	},
	btn: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		minWidth: 280,
		height: 36,
		paddingVertical: 8,
		paddingHorizontal: 30,
		fontSize: 16,
		fontWeight: '500',
		lineHeight: 20,
		color: '#ffffff',
		backgroundColor: '#3498db',
		borderRadius: 10,
		boxShadow: '0px 4px 8px rgba(64, 123, 255, 0.4)',
	},
	rightSide: {
		display: 'block',
		paddingVertical: 24,
		paddingHorizontal: 16,
		maxWidth: 248,
		marginLeft: 'auto',
		marginRight: 'auto',
		backgroundColor: '#ecf2ff',
		borderRadius: 10,
		boxShadow: '0px 4px 14px 0px rgba(64, 123, 255, 0.3)',
	},
	titleRight: {
		marginBottom: 12,
		fontWeight: '500',
		fontSize: 18,
		lineHeight: 20,
	},
	listRight: {
		flexDirection: 'column',
		gap: 16,
	},
	itemRight: {
		flexDirection: 'row',
		gap: 8,
		alignItems: 'center',
		paddingLeft: 16,
		fontWeight: '400',
		fontSize: 16,
		lineHeight: 20,
		position: 'relative',
	},
	homeWrapper: {
		padding: 24,
		paddingTop: 24,
		paddingBottom: 40,
		backgroundImage: 'url("path_to_your_image")',
		backgroundSize: 'cover',
		backgroundRepeat: 'no-repeat',
		backgroundPosition: 'center',
	},
	home: {
		padding: 32,
		paddingTop: 40,
		paddingBottom: 50,
		backgroundPosition: 'bottom',
		backgroundSize: 'cover',
		backgroundImage: 'url("path_to_your_image")',
	},
	svg: {
		width: 32,
		height: 32,
	},
});

export default styles;